# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :sweep do |options|
    begin
      sh 'rm -rf ./test_output'
    rescue
    end

    test_run_block = lambda do |testrun_info|
      failed_test_count = testrun_info[:failed].size

      if failed_test_count > 0
        UI.important('The run of tests would finish with failures due to fragile tests here.')

        try_attempt = testrun_info[:try_count]
        if try_attempt < 3
          UI.header('Since we are using :multi_scan, we can re-run just those failing tests!')
        end
      end
    end

    result = multi_scan(
      try_count: 3,
      fail_build: false,
      scheme: 'collate errors',
      result_bundle: true,
      device: "iPhone Xʀ (12.2)",
      testrun_completed_block: test_run_block,
      output_directory: './fastlane/test_output',
      output_types: 'junit,html',
      buildlog_path: './fastlane/test_output/',
      code_coverage: true,
      invocation_based_tests: false,
      parallel_testrun_count: 3
    )
    unless result[:failed_testcount].zero?
      UI.message("There are #{result[:failed_testcount]} legitimate failing tests")
    end
  end
end
